# recipes/recipe.yml
name: UrsaOS
description: Forged by Magic. Built with Logic.
base-image: ghcr.io/ublue-os/bazzite  # KDE + Nvidia (Best for AI/CUDA)
image-version: stable

modules:
  # 1. Add Repositories for your WMs
  - type: rpm-ostree
    repos:
      # Hyprland (Solopasha is the gold standard for Fedora)
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      # Niri (Official)
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      # Qtile (Official Python-based WM)
      - https://copr.fedorainfracloud.org/coprs/frostyx/qtile/repo/fedora-%OS_VERSION%/frostyx-qtile-fedora-%OS_VERSION%.repo
      # Terra (For MangoWC)
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo

    # 2. Install Packages (The Meat)
    install:
      # --- Window Managers ---
      - hyprland
      - niri
      - mangowc
      - qtile
      - qtile-extras
      - python3-pip           # Needed for Qtile widgets
      - python3-psutil        # Common Qtile dependency

      # --- Editors ---
      - neovim
      - zed

      # --- Development & Shell ---
      - fish
      - bash
      - zsh
      - git
      - gh
      - kitty             # Safety terminal
      
      # --- AI / Hardware Support ---
      # Bazzite-nvidia handles the drivers, but we ensure tools are here
      - nvtop                 # GPU monitoring

      # --- Desktop Portal & Fallbacks ---
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gnome # Good fallback for other WMs
      - sddm-wayland-plasma      # Ensures you can pick Qtile at login

    
  # 3. Flatpaks (GUI Apps - Pre-seeded)
  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          name: flathub
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
        install:
          - dev.vencord.Vesktop
          - com.spotify.Client
          - io.github.zen_browser.zen
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          - com.vysp3r.ProtonPlus

  # 4. The Setup Script
  - type: script
    scripts:
      - setup-ursa.sh

  

   
